# Generated by Django 5.1.7 on 2025-04-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductBrand",
            new_name="Brand",
        ),
    ]
