# Generated by Django 5.1.7 on 2025-04-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_productbrand_brand"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="brand",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[],
        ),
    ]
